# Generated by Django 3.2.9 on 2021-12-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.AddField(
            model_name='post',
            name='postDesc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='postTitle',
            field=models.CharField(default='Some Good Recipe', max_length=255),
            preserve_default=False,
        ),
    ]
