# Generated by Django 3.2.9 on 2021-12-04 17:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='a', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
