# Generated by Django 3.2.9 on 2021-12-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
