# Generated by Django 3.2.9 on 2021-12-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userName',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
    ]
